name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "slides/**"
      - "common/**"
      - "scripts/**"
      - "config.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install -g reveal-md
          npm install

      - name: Build slides
        run: |
          mkdir -p dist
          # 构建所有幻灯片
          for slide in slides/*/src; do
            echo "Building ${slide}..."
            make -C "${slide}" build || exit 1
          done
          # 生成索引页面
          node scripts/generate-index.js
          # 验证构建
          [ -d dist ] || exit 1
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
